apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gab
  description: gabapp
  annotations:
    github.com/project-slug: {{cookiecutter.storePath | jsonify}}
    backstage.io/techdocs-ref: github:https://github.com/{{cookiecutter.storePath}}
spec:
  type: service
  lifecycle: experimental
  owner: {{cookiecutter.owner | jsonify}}
